terraform {
  required_version = ">= 1.3"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# -----------------------------------------------------------------------------
# Example: Deploy with a pre-existing GitHub App using direct credentials.
#
# Use this when you already have a GitHub App and want to pass its credentials
# directly (e.g. from a Terraform variable or secrets manager). The webhook
# secret is auto-generated by the module when not provided.
# -----------------------------------------------------------------------------

module "octo_sts" {
  source = "../../"

  name = "octo-sts"

  github_app_config = {
    app_id      = var.github_app_id
    private_key = var.github_app_private_key
    # webhook_secret is auto-generated if not provided.
  }

  # Empty domain = use the API Gateway endpoint hostname for audience validation.
  sts_config = {
    domain = ""
  }
}
